### ISSUE TITLE
elf start error

### ISSUE THREAD

**Issue by littlebaozi** [o2team/elf#41]
#### ELF 版本
v1.9.1
#### 运行环境
windows 10 1803
node v9.4.0
npm v5.6.0
#### 报错信息
```bash
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8000
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at Server.setupListenHandle [as _listen2] (net.js:1366:14)
    at listenInCluster (net.js:1407:12)
    at Server.listen (net.js:1495:7)
    at Server.listen (D:\DevTool\nvm\v9.4.0\node_modules\elf-cli\node_modules\webpack-dev-server\lib\Server.js:479:47)
    at runDevServer (D:\DevTool\nvm\v9.4.0\node_modules\elf-cli\src\start.js:71:13)
    at run (D:\DevTool\nvm\v9.4.0\node_modules\elf-cli\src\start.js:88:3)
    at Object.<anonymous> (D:\DevTool\nvm\v9.4.0\node_modules\elf-cli\src\start.js:92:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
```

**Comment by booxood** [comment]
8000 端口已被占用了
