### ISSUE TITLE
Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime

### ISSUE THREAD

**Issue by love-zhen** [o2team/elf#43]
#### ELF 版本
1.9.1
#### 运行环境
window 10 64位 专业版

#### 操作流程
1. `elf init demo`
2. `yarn`
3. `elf start`
#### 报错信息
```
ERROR in C:/Users/DELL/AppData/Roaming/npm/node_modules/elf-cli/node_modules/css-loader?{}!C:/Users/DELL/AppData/Roaming/npm/node_modules/elf-cli/node_modules/postcss-loader/lib?{}!C:/Users/DELL/AppData/Roaming/npm/node_modules/elf-cli/node_modules/sass-loader/lib/loader.js!./src/css/package.scss
Module build failed: Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.5.3
    at module.exports (C:\Users\DELL\AppData\Roaming\npm\node_modules\elf-cli\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\DELL\AppData\Roaming\npm\node_modules\elf-cli\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\DELL\AppData\Roaming\npm\node_modules\elf-cli\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
 @ ./src/css/package.scss 4:14-371 18:2-22:4 19:20-377
 @ ./src/js/main.js
 @ multi (webpack)-dev-server/client?/ (webpack)/hot/dev-server.js src/js/main.js

  Compiling fail!
```

**Comment by love-zhen** [comment]
吐槽一下，下载好慢，我想下载其他模板，一直不懂，伤心

**Comment by chuyik** [comment]
请跟着文档操作，node-sass 需要用国内源。
```
# windows
$ npm install -g elf-cli --registry=https://registry.npm.taobao.org --SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/ --PHANTOMJS_CDNURL=https://npm.taobao.org/mirrors/phantomjs/
```

**Comment by love-zhen** [comment]
@chuyik 嗨，谢谢，我用了别人提供的方式解决了，我是切换成淘宝镜像进行操作的

[解决](https://github.com/Microsoft/PartsUnlimited/issues/134)

```
npm --depth 9999 update
npm rebuild node-sass
```
