### ISSUE TITLE
phantomjs下载非常耗时

### ISSUE THREAD

**Issue by liaojunhao** [o2team/elf#46]
1）安装失败
Phantom installation failed Error: end of central directory record signature not found
    at /usr/local/lib/node_modules/elf-cli/node_modules/extract-zip/node_modules/yauzl/index.js:167:14
    at /usr/local/lib/node_modules/elf-cli/node_modules/extract-zip/node_modules/yauzl/index.js:473:5
    at /usr/local/lib/node_modules/elf-cli/node_modules/extract-zip/node_modules/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5) Error: end of central directory record signature not found
    at /usr/local/lib/node_modules/elf-cli/node_modules/extract-zip/node_modules/yauzl/index.js:167:14
    at /usr/local/lib/node_modules/elf-cli/node_modules/extract-zip/node_modules/yauzl/index.js:473:5
    at /usr/local/lib/node_modules/elf-cli/node_modules/extract-zip/node_modules/fd-slicer/index.js:32:7
    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5)

2）phantomjs
这个包很耗时看这个能不能优化一下？

**Comment by booxood** [comment]
看错误估计是 phantomjs 下载没成功

因为依赖的库 postcss-sprites 里有  phantomjs，所以需要安装。
```
elf-cli@1.9.1 /Users/liuchuwen/O2team/elf
└─┬ postcss-sprites@4.2.1
  └─┬ svg-sprite@1.4.0
    └── phantomjs-prebuilt@2.1.16
```
