### ISSUE TITLE
npm install失败

### ISSUE THREAD

**Issue by Alwayslazydog** [o2team/elf#48]
#### ELF 版本
npm失败
不论是全局代理还是淘宝，还是官方推荐都试过惹
MAC 跟 windows下面都不行
#### 运行环境
node v12.13.0
npm v6.12

#### 报错信息
Writing location.js file
Done. Phantomjs binary available at C:\Users\Hoga.SC-201910080547\AppData\Roaming\npm\node_modules\elf-cli\node_modules\   phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> node-sass@4.5.3 install C:\Users\Hoga.SC-201910080547\AppData\Roaming\npm\node_modules\elf-cli\node_modules\node-sass    > node scripts/install.js

Downloading binary from https://npm.taobao.org/mirrors/node-sass//v4.5.3/win32-x64-72_binding.node
Cannot download "https://npm.taobao.org/mirrors/node-sass//v4.5.3/win32-x64-72_binding.node":

HTTP error 404 Not Found

  ‼ read ECONNRESET
  ‼ pngquant pre-build test failed
  i compiling from source
  √ pngquant pre-build test passed successfully
  × Error: pngquant failed to build, make sure that libpng-dev is installed
    at C:\Users\Hoga.SC-201910080547\AppData\Roaming\npm\node_modules\elf-cli\node_modules\pngquant-bin\node_modules\bin-build\node_modules\execa\index.js:231:11
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Alwayslazydog** [comment]
@booxood Orz

**Comment by booxood** [comment]
@Alwayslazydog  这个库 `pngquant` 安装失败了。你先试下单独安装成功后（[kornelski/pngquant](https://github.com/kornelski/pngquant)），再尝试。
